export const GET_UNITS_REQUEST = 'GET_UNITS_REQUEST';
export const GET_UNITS_FAILURE = 'GET_UNITS_FAILURE';
export const GET_UNITS_SUCCESS = 'GET_UNITS_SUCCESS';

export const FILTER_UNIT = 'FILTER_UNIT';